### PR TITLE
Fix failure when early calling to `focus()` 

### PR DESCRIPTION
**Pull request by manolo**
Fixes https://github.com/vaadin/vaadin-list-box/issues/13

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/23)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[bower.json, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23#-KzShRM3jkx-7t1m2BnO:-KzShRM3jkx-7t1m2BnP:bu60dmy) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/f181683fc30af4ced2094c26e205b3aff974b337/bower.json#L29)):*
> ```JSON
>     "polymer": "^2.0.0",
>     "vaadin-themable-mixin": "^1.1.3",
>     "vaadin-context-menu": "^2.0.0"
> ```

Should be a dev dependency

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23)*

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23)*

**Comment by tomivirkki** [comment]
*[vaadin-list-mixin.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23#-KzSmpQeWpo85jOO7-1b:-KzSmpQeWpo85jOO7-1c:b-8qgki6) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e97d56ac99a98d095c6e0e32ef6b01b9dda46f11/vaadin-list-mixin.html#L61)):*
> ```HTML
>       this.addEventListener('click', e => this._onClick(e));
> 
>       Polymer.RenderStatus.afterNextRender(this, () => {
> ```

Simpler fix would be to remove this `afterNextRender`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23)*

**Comment by tomivirkki** [comment]
*[bower.json, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23#-KzShRM3jkx-7t1m2BnO:-KzT4m5ozW8UigY8nXa8:b-886gsx) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/f181683fc30af4ced2094c26e205b3aff974b337/bower.json#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should be a dev dependency
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23)*

**Comment by tomivirkki** [comment]
*[vaadin-list-mixin.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23#-KzSmpQeWpo85jOO7-1b:-KzT4pRv_V-6YazHH2Yg:b-886gsx) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e97d56ac99a98d095c6e0e32ef6b01b9dda46f11/vaadin-list-mixin.html#L61)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Simpler fix would be to remove this `afterNextRender`
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23#-:-KzT4tFnLIOYMbwH3FYt:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/23#-:-KzT5XVz8SYzdO1cL0EE:bnfp4nl)*

**Pull request merged**
