### PR TITLE
Move selection logic to list mixin

### PR DESCRIPTION
**Pull request by manolo**
- Compute _navItems when the dom is modified, instead of each time it's used.
- Move code to set selected to the list mixin.

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/16)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-list-mixin.html, line 98 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/16#-KxD_X921UpRvcKY6wB4:-KxD_X921UpRvcKY6wB5:b-74fkri) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/0eaf145d590ac9f61222dd4e37ad6e93d0e36a46/vaadin-list-mixin.html#L98)):*
> ```HTML
>         this.selected = idx;
>       }
>       return;
> ```

nit: This looks unnecessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/16#-:-KxD_dPl_-uj2tZ3bDlg:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-list-mixin.html, line 98 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/16#-KxD_X921UpRvcKY6wB4:-KxDzJGY_hObN2zY6Swz:b-chsqel) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/0eaf145d590ac9f61222dd4e37ad6e93d0e36a46/vaadin-list-mixin.html#L98)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: This looks unnecessary
</blockquote></details>

Yep :-)  , I had that block in another place and moved as well the return

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/16)*

**Comment by manolo** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/16)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/16)*

**Pull request merged**
