### PR TITLE
Rename property `vertical` to `orientiation`.

### PR DESCRIPTION
**Pull request by manolo**
Connects to https://github.com/vaadin/vaadin-core/issues/105

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/8)

### CODE REVIEW

**Comment by limonte** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-list-item-mixin.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-Kwt4lYGrvmEQkjC_7c_:-Kwt4lYGrvmEQkjC_7ca:b-a7ui0q) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e5a12e916be781a5924d72feea65816ff9ac9611/vaadin-list-item-mixin.html#L71)):*
> ```HTML
> 
>     _toggle() {
>       if (!this.disabled) {
> ```

This is out of the PR scope. Should be ideally in separated PR, but at least in the separated commit.

---

*[vaadin-list-mixin.html, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-Kwt4tgzGsSEklVuLfja:-Kwt4tgzGsSEklVuLfjb:b-cn0ydu) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e5a12e916be781a5924d72feea65816ff9ac9611/vaadin-list-mixin.html#L30)):*
> Possible values are: `horizontal|vertical`

> value: ''

There's no `''` in possible values list, should it be `'vertical'` by default?

---

*[vaadin-list-mixin.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-Kwt592RW-9t3gZXr0VJ:-Kwt592RW-9t3gZXr0VK:b1dfgez) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e5a12e916be781a5924d72feea65816ff9ac9611/vaadin-list-mixin.html#L47)):*
> ```HTML
>       this.addEventListener('keydown', e => this._onKeydown(e));
>       this.shadowRoot.querySelectorAll('slot').forEach(slot => {
>         slot.addEventListener('slotchange', e => this._updateItemsOrientiation());
> ```

`e` is defined but never used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Comment by manolo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-list-item-mixin.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-Kwt4lYGrvmEQkjC_7c_:-Kwt6F4EWYO7aDmmqBSk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e5a12e916be781a5924d72feea65816ff9ac9611/vaadin-list-item-mixin.html#L71)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This is out of the PR scope. Should be ideally in separated PR, but at least in the separated commit.
</blockquote></details>

Done.

---

*[vaadin-list-mixin.html, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-Kwt592RW-9t3gZXr0VJ:-Kwt6J4vIOdga1LZtECO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e5a12e916be781a5924d72feea65816ff9ac9611/vaadin-list-mixin.html#L47)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`e` is defined but never used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Comment by manolo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-list-mixin.html, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-Kwt4tgzGsSEklVuLfja:-Kwt6fCBGlTv32Fj8zzu:b-x9y71z) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e5a12e916be781a5924d72feea65816ff9ac9611/vaadin-list-mixin.html#L30)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> Possible values are: `horizontal|vertical`

> value: ''

There's no `''` in possible values list, should it be `'vertical'` by default?
</blockquote></details>

`undefined` does not fires the first call to orientationChanged to set aria. This is the easiest way to  trigger that, otherwise it could be null or add a manual call in ready which is more code. Setting it empty makes the best sense to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-:-KwtAKc1QiiPeoykH4vB:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-list-item-mixin.html, line 87 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-KwtAzzXVvR8ywXqHrkk:-KwtAzzXVvR8ywXqHrkl:b-gc5u16) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/f31ed45593f901ce32e44c29e15df85f3a7f3ee9/vaadin-list-item-mixin.html#L87)):*
> ```HTML
>         this.blur();
>       } else {
>         this.selected = false;
> ```

Shouldn't this be changed to false also when disabled is set true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Comment by manolo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-list-item-mixin.html, line 87 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-KwtAzzXVvR8ywXqHrkk:-KwtCAnmS_K7-UfDv7L5:b-rgle3y) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/f31ed45593f901ce32e44c29e15df85f3a7f3ee9/vaadin-list-item-mixin.html#L87)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Shouldn't this be changed to false also when disabled is set true?
</blockquote></details>

This line was in the wrong place. Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Comment by tomivirkki** [comment]
*[vaadin-list-item-mixin.html, line 87 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-KwtAzzXVvR8ywXqHrkk:-KwtCiBJD66LnEv85TFI:b-fuym6x) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/f31ed45593f901ce32e44c29e15df85f3a7f3ee9/vaadin-list-item-mixin.html#L87)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This line was in the wrong place. Fixed
</blockquote></details>

Should have probably broken a test 🤔

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-:-KwtB_Fk8j-vLzpAWL3f:bnfp4nl)*

**Comment by manolo** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[vaadin-list-item-mixin.html, line 87 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8#-KwtAzzXVvR8ywXqHrkk:-KwtDjrfXnwrGMvPoXVP:b-7d8jpq) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/f31ed45593f901ce32e44c29e15df85f3a7f3ee9/vaadin-list-item-mixin.html#L87)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should have probably broken a test 🤔
</blockquote></details>

Actually the test had a bad assertion, I fixed both the line and the test in the squash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/8)*

**Pull request merged**
