### PR TITLE
Update dependencies. Rename vars in tests.

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/25)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-list-mixin.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/25#-KzT_Z0F0st0595lYNAL:-KzT_Z0F0st0595lYNAM:b-v0m5oc) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/5dac569e14fe7b31a855944275f7552267070846/test/vaadin-list-mixin.html#L153)):*
> ```HTML
> 
>     describe('vaadin-list-mixin', () => {
>       var list;
> ```

OK not a blocker, but `let list;` please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/25)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-list-mixin.html, line 153 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/25#-KzT_Z0F0st0595lYNAL:-KzTc072b4M6kBeVCn7O:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/5dac569e14fe7b31a855944275f7552267070846/test/vaadin-list-mixin.html#L153)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK not a blocker, but `let list;` please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/25)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/25#-:-KzTsu4XELpRWT2OAWhw:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/25#-:-KzTvPHDXNt4HnheFuD8:bnfp4nl)*

**Pull request merged**
