### PR TITLE
Fixes for context menu

### LINKED ISSUE #12: vaadin-list-mixin: Should have a `focus()` method
call to `focus()` should focus the element with `tabIndex=0`.
It's needed for integration with context-menu

### PR DESCRIPTION
**Pull request by manolo**
Connected to #https://github.com/vaadin/vaadin-context-menu/issues/110
Fixes #12 #13

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/14)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Keyboard navigation doesn't work in the demo. Can't test this live

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-:-Kx6uRFnD0M0o9TAOcjg:b-r5c0af)*

**Comment by manolo** [comment]
Updated demos, and fixed that list-item mixin should be loaded before querying the dom.
Note that vaadin-tabs demo in vertical does not work unless you depend on the rename-vertical branch

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-:-Kx6wiQjn51sYLSyVd46:b-49cg92)*

**Comment by manolo** [comment]
Note: For the drop down menu demo you need to depend on the prototype PR branch

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-:-Kx7cgD8hPkXjuReSbeW:bgsq1y6)*

**Comment by tomivirkki** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-list-mixin.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-Kx7ic7g8JQUjN7bc5ub:-Kx7ic7g8JQUjN7bc5uc:b-tju8yc) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e2a8823c1f32f89f88c90a23bad0ae47fde1474f/vaadin-list-mixin.html#L52)):*
> ```HTML
> 
>       // We need to wait until the dom is ready so as ListItemElements have been initialised.
>       Polymer.RenderStatus.afterNextRender(this, () => {
> ```

Why do we need to make this element asynchronous? There's no test to justify this.

---

*[vaadin-list-mixin.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-Kx7jJK6jIsY26UMcqze:-Kx7jJK6jIsY26UMcqzf:b-dg6j47) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e2a8823c1f32f89f88c90a23bad0ae47fde1474f/vaadin-list-mixin.html#L145)):*
> ```HTML
>     focus() {
>       const items = this._navItems;
>       this._focus(items.indexOf(this.querySelector('[tabindex="0"]') || items[0]));
> ```

Shouldn't moving the focus to the child item be enough here? `(this.querySelector('[tabindex="0"]') || this._navItems[0]).focus();`

If it doesn't work then does it mean `item.focus()` is broken?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14)*

**Comment by YuriyVaadin** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14)*

**Comment by manolo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-list-mixin.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-Kx7ic7g8JQUjN7bc5ub:-Kx83R7C2kRdCrWs8tf_:b-2ztfmm) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e2a8823c1f32f89f88c90a23bad0ae47fde1474f/vaadin-list-mixin.html#L52)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why do we need to make this element asynchronous? There's no test to justify this.
</blockquote></details>

As explained in chat, `this._navItems` needs the DOM to be ready before figuring out children items.

---

*[vaadin-list-mixin.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-Kx7jJK6jIsY26UMcqze:-Kx83tCYTEkEal5TVj1V:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/e2a8823c1f32f89f88c90a23bad0ae47fde1474f/vaadin-list-mixin.html#L145)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Shouldn't moving the focus to the child item be enough here? `(this.querySelector('[tabindex="0"]') || this._navItems[0]).focus();`

If it doesn't work then does it mean `item.focus()` is broken?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/14#-:-Kx8BmKpIydy9aeo9R_9:bnfp4nl)*

**Pull request merged**
