### PR TITLE
items needs to be in the same order than child nodes.

### LINKED ISSUE #33: When updating elements with `tabs.insertBefore`, `tabs.items` is not updated
Related with https://github.com/vaadin/vaadin-tabs-flow/issues/33

### PR DESCRIPTION
**Pull request by manolo**
Fixes #33

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/35)

### CODE REVIEW

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[test/vaadin-list-mixin.html, line 166 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/35#-L9R3kTSACZt_4Y46Ho1:-L9R3kTSACZt_4Y46Ho2:bsm944w) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/ab04df0e998883ede9ddcfafb0ffe23f597ed669/test/vaadin-list-mixin.html#L166)):*
> ```HTML
>         beforeEach(() => list._observer.flush());
> 
>         it('should update items list when removing nodes', () =>  {
> ```

eslint complains about extra whitespace here

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/35)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-list-mixin.html, line 166 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/35#-L9R3kTSACZt_4Y46Ho1:-L9RMQtj9-w1VRnHcpHU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/ab04df0e998883ede9ddcfafb0ffe23f597ed669/test/vaadin-list-mixin.html#L166)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

eslint complains about extra whitespace here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/35)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/35)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/35#-:-L9dSxEkAcM1HZ3PxBGC:bnfp4nl)*

**Pull request merged**
