### PR TITLE
Check defaultPrevented before clicking

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fix https://github.com/vaadin/vaadin-tabs/issues/72
Solving multiple (2+) clicks on tab.

**Previous incorrect behaviour (pressing ones, holding space):**
incorect-tab-click

**Fixed correct behaviour with this PR (pressing ones, holding space)**
right-tab-click

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/32)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-list-mixin.html, line 116 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/32#-L8H70Zt0eZWp06uhY_s:-L8WGdPuDCvY0XJ7_Sce:b-fvopzh) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/b7d1eee5e80544f8aa733c53b2f60832b36c649c/vaadin-list-mixin.html#L116)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Let's maybe keep this block and just use `return`, no need to proceed to the code section below.
The comment mentioning that `Vaadin.ItemMixin` is responsible of handling these keys and dispatching click events would be nice as well.
</blockquote></details>

I guess proceeding to the code below doesn't cause any issues either. There are lots of unhandled keys that will proceed anyway so wouldn't make sense the to exclude processing for two arbitrary ones?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/32)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-list-mixin.html, line 116 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/32#-L8H70Zt0eZWp06uhY_s:-L8WJ0xuHH6Yo3jc6fTt:b-syoxia) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/b7d1eee5e80544f8aa733c53b2f60832b36c649c/vaadin-list-mixin.html#L116)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I guess proceeding to the code below doesn't cause any issues either. There are lots of unhandled keys that will proceed anyway so wouldn't make sense the to exclude processing for two arbitrary ones?
</blockquote></details>

OK that makes sense. I agree to just keep those lines removed, so this method now only manages the focused element, not the selected one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/32)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/32#-:-L8WJqf9JvmLmBaLjEt0:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-list-mixin/32#-:-L8WKaolBjzJyqui8fmJ:bnfp4nl)*

**Pull request merged**
