### PR TITLE
Deselect items by setting selected to falsy or out-of-range value

### LINKED ISSUE #20: Unable to deselect all items
If we have a selected item, when setting `selected = undefined or -1 etc. `  previous value should be deselected but it does not.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #20

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-mixin/22)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-list-mixin.html, line 85 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-KyRIkD_a4HhVkW6fcGx:-KyRIkD_a4HhVkW6fcGy:b-nnrw2y) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/2f5671b705763c340da9c05780cd67db8dce7b9c/vaadin-list-mixin.html#L85)):*
> ```HTML
>         } else if (itemToSelect === undefined) {
>           items.forEach(item => item.selected = false);
>         }
> ```

This code might work in all cases

```
items.forEach(item => item.selected = item === itemToSelect);
if (itemToSelect && !itemToSelect.disabled) {
       this._scrollToItem(selected);
}
```

---

*[vaadin-list-mixin.html, line 151 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-KyRIFZI1n4zg2DHkARu:-KyRIFZJqfYnLeATfnOB:b1b7b6m) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/2f5671b705763c340da9c05780cd67db8dce7b9c/vaadin-list-mixin.html#L151)):*
> ```HTML
>       const totalItems = this._navItems.length;
>       const isValidIndex = idx !== undefined && idx !== null && !isNaN(idx);
>       for (let i = 0; isValidIndex && i < totalItems; i++, idx += (increment || 1)) {
> ```


`for (let i = 0; typeof idx == 'number' && i < totalItems; i++, idx += (increment || 1)) {'`

is simpler and covers more cases, like idx being a string, object, etc.

---

*[test/vaadin-list-mixin.html, line 182 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-KyRJXC8YRPseif7aHsY:-KyRJXC8YRPseif7aHsZ:b-tszwht) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/2f5671b705763c340da9c05780cd67db8dce7b9c/test/vaadin-list-mixin.html#L182)):*
> ```HTML
>         });
> 
>         it('should clear selection when `selected` property is set to negative value', () => {
> ```

There are so much tests here for a simple condition, I would just test by sending a not number, and use the typeof condition I mentioned

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-list-mixin.html, line 85 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-KyRIkD_a4HhVkW6fcGx:-KyS5cC3BBeDvzqgBwd7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/2f5671b705763c340da9c05780cd67db8dce7b9c/vaadin-list-mixin.html#L85)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This code might work in all cases

```
items.forEach(item => item.selected = item === itemToSelect);
if (itemToSelect && !itemToSelect.disabled) {
       this._scrollToItem(selected);
}
```

</blockquote></details>

Done.

---

*[vaadin-list-mixin.html, line 151 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-KyRIFZI1n4zg2DHkARu:-KyS5ddTM-OYRkHQ_geH:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/2f5671b705763c340da9c05780cd67db8dce7b9c/vaadin-list-mixin.html#L151)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>


`for (let i = 0; typeof idx == 'number' && i < totalItems; i++, idx += (increment || 1)) {'`

is simpler and covers more cases, like idx being a string, object, etc.
</blockquote></details>

Done.

---

*[test/vaadin-list-mixin.html, line 182 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-KyRJXC8YRPseif7aHsY:-KyS5ejcxcvj-zyRCNNh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-list-mixin/blob/2f5671b705763c340da9c05780cd67db8dce7b9c/test/vaadin-list-mixin.html#L182)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

There are so much tests here for a simple condition, I would just test by sending a not number, and use the typeof condition I mentioned
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-list-mixin/22#-:-KyZgdxUPRT2sxAp6UTg:bnfp4nl)*

**Pull request merged**
